#
# MuDiSP3 Makefile: newran03
#


# add any other block library directory here


EXTRACPPFLAGS = 


# add each source file

sources = 	newran1.cpp \
		newran2.cpp \
		myexcept.cpp \
		simpstr.cpp \
		myexcept.cpp \
		extreal.cpp




# add header path

install_include = newran.h \
		  include.h \
		  myexcept.h \
		  extreal.h \
		  simpstr.h


target_name = libnewran03


#######################################################################


include ../Makefile.lib

